### ISSUE TITLE
Inform user, to properly export ALL of subs, has to scroll all way down, to let them load

### ISSUE THREAD

**Issue by micielski** [ajohntom/tube-sub-export#1]
Inform user, to properly export ALL of subs, has to scroll all way down, to let them load
A small detail, but why not
Maybe make the script to load the page whole automatically? idk

**Comment by ajohntom** [comment]
Addressed. Now a very basic "scroll-to-bottom and see if there's any additional page content loading happens" fashioned solution is added. But in any case, there's an instruction field that suggests the user to do it manually, if XML is not correct.

Spent a little bit of time figuring out YT page based events, but after a few try, I eventually gave up, and did this very basic solution.
