### ISSUE TITLE
Does not work from subscriptions button w/o page reload

### ISSUE THREAD

**Issue by andry81** [ajohntom/tube-sub-export#2]
Browser: Firefox 98.0.1
Version: 0.1.4

If click subscriptions button from the page: https://www.youtube.com/feed/subscriptions
Then the button does not show w/o page reload.

Works if directly open the link: https://www.youtube.com/feed/channels

**Comment by ajohntom** [comment]
**It's not supposed to work from the https://www.youtube.com/feed/subscriptions link.**
As stated on the Firefox Add-On Gallery page, only works from the https://www.youtube.com/feed/channels link.
The logic is that previously the XML download was available on that page... so this extension behaves the same.

**It's not an issue, it supposed to work like this.**

**Comment by andry81** [comment]
> It's not supposed to work from the [youtube.com/feed/subscriptions](https://www.youtube.com/feed/subscriptions) link.

Yes, but this is official way go to the subscriptions page which *does not work* with plugin. You have had to state this clearly in the description in red.

**Comment by ajohntom** [comment]
The "official way" to download the XML in the past, was going to the "Subscription Manager" page, wich happens to be https://www.youtube.com/feed/channels. The https://www.youtube.com/feed/subscriptions page, is not about listing the channels you are subscribed, but to list the video feed of your subscriptions.

**Long story short, the original behaviour used to be what the extension now accomplishes.** And in my opinion in the Firefox Add-On Galery, it's directly stated in the description that it behaves this way. I updated the description here as well, for convenience.

**Anyway, please watch your tone. It's a free stuff, which I created and maintain in my spare time. There's nothing I HAD to do/add upon request/demand. Just to make things clear.**

**Comment by andry81** [comment]
> The "official way" to download the XML in the past, was going to the "Subscription Manager" page, wich happens to be [youtube.com/feed/channels](https://www.youtube.com/feed/channels). The [youtube.com/feed/subscriptions](https://www.youtube.com/feed/subscriptions) page, is not about listing the channels you are subscribed, but to list the video feed of your subscriptions.

No, the "official way" of the youtube itself. The page has a button/link to go to https://www.youtube.com/feed/channels . If press it, then the plugin won't work. This button/link exists on another page: https://www.youtube.com/feed/subscriptions

> **Anyway, please watch your tone. It's a free stuff, which I created and maintain in my spare time. There's nothing I HAD to do/add upon request/demand. Just to make things clear.**

I am helping you not offending you. Your description just misleading, this is all I've wanted to say.
